language: perl

perl:
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"
    - "5.28"

install:
    - cpanm -qn --installdeps .

notifications:
    recipients:
        - mirko@westermeier.de
    email:
        on_success: always
        on_failure: always
