#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::Loader 'load_class';

use lib map app->home->rel_file($_)->to_string => qw(lib viralgiral/lib);

# Version status: load now, report later
my @modules = qw(Mojolicious EventStore::Tiny ViralGiral Candelite);
load_class $_ for @modules;
get '/__versions__' => {
    perl_version    => $^V,
    module_version  => {map {
        $_      => eval('$' . $_ . '::VERSION')
    } @modules},
} => 'versions';

app->start;

__DATA__

@@ versions.html.ep
% layout 'default';
% title 'Versions';
<h1><%= title %></h1>
<p><strong id="perl-version">perl version: <%= $perl_version %></strong></p>
<table border="1" id="module-versions">
    <thead><tr><th>module</th><th>version</th></tr></thead>
    <tbody>
    % for my $mod (sort keys %$module_version) {
        <tr><th><%= $mod %></th><td><%= $module_version->{$mod} %></td></tr>
    % }
    </tbody>
</table>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
    <head><title>Candelite - <%= title %></title></head>
    <body><%= content %></body>
</html>
